In [ ]:
Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [10]:
import numpy as np

In [15]:
Z = np.arange(10)
Z = Z[::-1]
print(Z)

[9 8 7 6 5 4 3 2 1 0]


In [ ]:
Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [ ]:
f'введите количество элементов'
n=int(input())
matrix=np.diag(np.arange(n,0,-1))
summ=0
for line in matrix:
    for j in line:
        summ+=j
print(matrix)
print('сумма: {}'.format(summ))

In [ ]:
Задание 3
Решите систему уравнений:
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3

In [ ]:
from numpy import linalg
a=np.array([[4,2,1],[1,3,0],[0,5,4]])
b=np.array([4,12,-3])
linalg.solve(a,b)

In [ ]:
Задание 4
Имеется матрица покупок в интернет-магазине. 
Столбец А - ID пользователя. Остальные столбцы - количество покупок категорий товаров этим пользователем:

In [ ]:
Матрица в виде numpy array

In [3]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

In [ ]:
На сайт заходит очередной посетитель, о покупках которого известно следующее:

In [24]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

In [14]:
import math


In [ ]:
Найдите самого похожего пользователя. 
Т. е. посчитайте косинусное сходство между этим пользователем и всеми пользователями из массива user_stats

In [ ]:
Мне нужно применить cosine к каждой строке матрицы users_stats. В numpy для этого есть функция apply_along_axis:

In [25]:
def cosine( users_stats, next_user_stats ):
    # длины векторов
    users_stats_Length = np.linalg.norm( users_stats )
    next_user_stats_Length = np.linalg.norm( next_user_stats )
    
    return np.dot( users_stats, next_user_stats ) / ( users_stats_Length * next_user_stats_Length )

In [26]:
muls = np.apply_along_axis(cosine, 1, users_stats, next_user_stats)

In [ ]:
Второй аргумент 1 означает, что функция cosine должна вызываться для строк. 
Последний аргумент next_user_stats будет подставляться вторым аргументом в cosine. 
Вызов этой функции эквивалентен вот какому коду на Python:

In [27]:
muls = np.array([cosine(row, next_user_stats) for row in users_stats])

In [ ]:
В обоих случаях результат равен

In [26]:
Функция np.argmax находит индекс элемента, который соответствует максимальному значению массива (нумерация с нуля):

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [28]:
best_user = np.argmax(muls)

In [29]:
best_user

7